<a href="https://colab.research.google.com/github/willveloso/python_advanced/blob/main/04_Estilizacao_de_tabelas_aula1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coleta e preparação de dados

In [ ]:
#!pip install pandas==2.0.0

In [ ]:
# Montando o drive no Google Drive para acessar o arquivo fonte de dados

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Alura - Python para Data Science - Avançado/relatorio_vendas.csv')
df

,data_pedido,data_envio,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,preco_base,preco_unit_sem_desc,desconto,preco_unit_venda,quantidade,vendas,lucro
0,2018-11-09,2018-11-12,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,encanamentos,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Econômica,Thiago Silveira,B2C,Ribeirão Preto,São Paulo,Sudeste,Materiais de construção,ferramentas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Econômica,Giovanna Lima,B2B,Rio de Janeiro,Rio de Janeiro,Sudeste,Jardinagem e paisagismo,sementes,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Materiais de construção,materiais de revestimento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega padrão,Ana Júlia da Cruz,B2C,Foz do Iguaçu,Paraná,Sul,Jardinagem e paisagismo,vasos,35.88,42.24,0.100,38.02,2,76.04,4.28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2018-09-30,2018-10-04,Entrega padrão,Enrique Santos,B2C,Rio de Janeiro,Rio de Janeiro,Sudeste,Automotivo,ferramentas automotivas,97.34,123.22,0.000,123.22,1,123.22,25.88
8936,2019-11-18,2019-11-22,Entrega padrão,Heitor Silveira,B2B,Jequié,Bahia,Nordeste,Automotivo,ferramentas automotivas,223.01,271.97,0.000,271.97,1,271.97,48.96
8937,2019-11-18,2019-11-22,Entrega padrão,Heitor Silveira,B2B,Jequié,Bahia,Nordeste,Automotivo,pneus,121.23,140.15,0.000,140.15,5,700.75,94.60
8938,2016-01-22,2016-01-24,Econômica,Isabel Araújo,B2C,João Pessoa,Paraíba,Nordeste,Materiais de construção,iluminação,26.29,31.79,0.100,28.61,3,85.83,6.96
8939,2019-05-05,2019-05-10,Econômica,Esther Rodrigues,B2C,Mossoró,Rio Grande do Norte,Nordeste,Jardinagem e paisagismo,mobiliário de exterior,351.36,413.37,0.000,413.37,2,826.74,124.02

In [ ]:
# Visualizando os tipos de dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data_pedido          8940 non-null   object
 1   data_envio           8940 non-null   object
 2   modo_envio           8940 non-null   object
 3   nome_cliente         8940 non-null   object
 4   segmento_cliente     8940 non-null   object
 5   cidade               8940 non-null   object
 6   estado               8940 non-null   object
 7   regiao               8940 non-null   object
 8   departamento         8940 non-null   object
 9   tipo_produto         8940 non-null   object
 10  preco_base           8940 non-null   float64
 11  preco_unit_sem_desc  8940 non-null   float64
 12  desconto             8940 non-null   float64
 13  preco_unit_venda     8940 non-null   float64
 14  quantidade           8940 non-null   int64
 15  vendas               8940 non-null   float64
 16  lucro                8940 non-null   float64
dtypes: float64(6), int64(1), object(10)
memory usage: 1.2+ MB

In [ ]:
df['data_pedido'] = pd.to_datetime(df['data_pedido'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data_pedido          8940 non-null   datetime64[ns]
 1   data_envio           8940 non-null   object
 2   modo_envio           8940 non-null   object
 3   nome_cliente         8940 non-null   object
 4   segmento_cliente     8940 non-null   object
 5   cidade               8940 non-null   object
 6   estado               8940 non-null   object
 7   regiao               8940 non-null   object
 8   departamento         8940 non-null   object
 9   tipo_produto         8940 non-null   object
 10  preco_base           8940 non-null   float64
 11  preco_unit_sem_desc  8940 non-null   float64
 12  desconto             8940 non-null   float64
 13  preco_unit_venda     8940 non-null   float64
 14  quantidade           8940 non-null   int64
 15  vendas               8940 non-null   float64
 16  lucro                8940 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1), object(9)
memory usage: 1.2+ MB

# Missão 1: Time de vendas

Precisamos construir uma visualização para indicar os **10 maiores clientes por total de venda**.

Com isso, a equipe de vendas pode pensar em estratégias para manter esses clientes comprando em nossa loja.

In [ ]:
df_cliente_vendas = df.groupby(['nome_cliente'])['vendas'].sum().nlargest(10).copy()
df_cliente_vendas = df_cliente_vendas.reset_index()
df_cliente_vendas

            nome_cliente    vendas
0    Maria Luiza Almeida  64777.52
1        Ana Julia Pinto  51398.87
2            Ryan Farias  48178.99
3         Heitor da Mata  47610.80
4  Maria Clara Gonçalves  46946.38
5         Raquel Freitas  44826.25
6             Davi Ramos  43769.25
7            Amanda Melo  42354.19
8         Alexia Ribeiro  41238.81
9         Calebe Ribeiro  41056.80

In [ ]:
df_cliente_vendas.columns = ['Clientes','Vendas']
df_cliente_vendas['Ranque'] = df_cliente_vendas.index + 1
df_cliente_vendas.set_index('Ranque', inplace = True)
df_cliente_vendas

                     Clientes    Vendas
Ranque
1         Maria Luiza Almeida  64777.52
2             Ana Julia Pinto  51398.87
3                 Ryan Farias  48178.99
4              Heitor da Mata  47610.80
5       Maria Clara Gonçalves  46946.38
6              Raquel Freitas  44826.25
7                  Davi Ramos  43769.25
8                 Amanda Melo  42354.19
9              Alexia Ribeiro  41238.81
10             Calebe Ribeiro  41056.80

In [ ]:
s = df_cliente_vendas.style
s

In [ ]:
s.format({'Vendas':'R$ {:,.2f}'})
s

# Missão 2: Time comercial

Precisamos construir uma visualização que permita associar o **total ganho em vendas e o total lucrado por tipo de produto**.

Isso vai permitir que o time comercial possa focar em estratégias para alavancar as rendas que ganham com cada tipo de produto vendido na loja.

In [ ]:
df_venda_produto = df.groupby(['tipo_produto'])[['vendas', 'lucro']].sum()
df_venda_produto.index.name = 'tipo_produto'
df_venda_produto

                               vendas     lucro
tipo_produto
decoração de jardim          82680.08   9939.43
encanamentos                373223.88  -5622.34
equipamentos de limpeza     542304.58   8724.39
ferramentas                 995158.41  41020.34
ferramentas automotivas     502109.29  63330.22
ferramentas de jardinagem   648879.72  53202.88
fertilizantes                53144.74  11254.88
iluminação                  275229.53  20264.54
materiais de paisagismo     150552.49  -1912.37
materiais de revestimento   629656.36 -28869.01
mobiliário de exterior      328932.27  26784.59
mudas                         8811.32   1381.42
pesticidas                  244956.04  53343.89
peças de reposição          486907.94  91148.67
pneus                      1022428.97  67460.05
sementes                     39979.75   8865.09
vasos                       696044.18  33941.85

In [ ]:
estilo_produto = df_venda_produto.style
estilo_produto

In [ ]:
estilo_produto.format('R$ {:,.2f}')\
                .highlight_max(color = 'lightgreen')\
                .highlight_min(color = '#F16165')
estilo_produto

In [ ]:
estilo_produto.format('R$ {:,.2f}').background_gradient(cmap = 'Greens')
estilo_produto

In [ ]:
# Formatando com CSS

cabecalho = {
    'selector':'th',
    'props':'font-weight: bold; font-family: Arial; text-align: center; text-transform: capitalize;'
}
estilo_produto.set_table_styles([cabecalho], overwrite = False)

# Missão 3: Time de logística

Precisamos construir uma visualização que permita entender a **distribuição de pedidos por região do Brasil**.

Isso vai permitir que o time logística entenda onde é mais interessante focar material e pessoas.

In [ ]:
df_regiao = pd.DataFrame(df['regiao'].value_counts())
df_regiao.columns = ['Nº pedidos']
df_regiao

              Nº pedidos
regiao
Sudeste             4470
Nordeste            2075
Centro-Oeste         983
Norte                779
Sul                  633

In [ ]:
df_regiao.index.name = 'Região'

In [ ]:
import numpy as np

In [ ]:
porcentagem = df_regiao['Nº pedidos'].to_numpy()
porcentagem = 100 * porcentagem / porcentagem.sum()
porcentagem

array([50.        , 23.21029083, 10.99552573,  8.71364653,  7.08053691])

In [ ]:
df_regiao['Porcentagem regiao'] = porcentagem
df_regiao

              Nº pedidos  Porcentagem regiao
Região
Sudeste             4470           50.000000
Nordeste            2075           23.210291
Centro-Oeste         983           10.995526
Norte                779            8.713647
Sul                  633            7.080537

In [ ]:
estilo_regiao = df_regiao.style
estilo_regiao

In [ ]:
cabecalho = {
    'selector':'th',
    'props':'font-weight: bold; font-family: Arial; text-align: right; background-color: black;'
}
celulas = {
    'selector':'td',
    'props':'background-color: black;'
}

estilo_regiao.set_table_styles([cabecalho, celulas])

In [ ]:
estilo_regiao.format({'Porcentagem regiao':'{:.2f} %'})\
            .bar(subset = 'Porcentagem regiao', vmin = 0, vmax = 100.0, color = '#9CD33B')

# Missão 4: Time de logística

Novamente o time de logística deseja repensar sua estrutura e organização de fornecimento de produtos e para isso, foi pensada em uma visualização que permita identificar padrão de **quantidade de produtos solicitados por mês por departamento**.

In [ ]:
df_meses = df.copy()
df_meses = df_meses.sort_values('data_pedido')

In [ ]:
# Criando a coluna de 'Ano - Mês'

df_meses['meses'] = df_meses['data_pedido'].dt.strftime('%Y - %b')
df_meses = df_meses.reset_index(drop = True)
df_meses

,data_pedido,data_envio,modo_envio,nome_cliente,segmento_cliente,cidade,estado,regiao,departamento,tipo_produto,preco_base,preco_unit_sem_desc,desconto,preco_unit_venda,quantidade,vendas,lucro,meses
0,2016-01-04,2016-01-08,Entrega padrão,Ana Júlia Monteiro,B2C,Belo Horizonte,Minas Gerais,Sudeste,Jardinagem e paisagismo,pesticidas,23.24,31.07,0.1,27.96,2,55.92,9.44,2016 - Jan
1,2016-01-05,2016-01-09,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,10.68,10.03,0.4,6.02,2,12.04,-9.32,2016 - Jan
2,2016-01-05,2016-01-09,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,vasos,345.81,343.44,0.1,309.10,3,927.30,-110.13,2016 - Jan
3,2016-01-05,2016-01-09,Entrega padrão,Maria Cecília Jesus,B2B,Botucatu,São Paulo,Sudeste,Jardinagem e paisagismo,sementes,10.94,14.84,0.1,13.36,3,40.08,7.26,2016 - Jan
4,2016-01-06,2016-01-13,Entrega padrão,Marcelo Rezende,B2C,Brasília,Distrito Federal,Centro-Oeste,Jardinagem e paisagismo,decoração de jardim,19.37,24.60,0.1,22.14,3,66.42,8.31,2016 - Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2019-12-31,2020-01-04,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,48.60,66.46,0.1,59.81,3,179.43,33.63,2019 - Dec
8936,2019-12-31,2020-01-04,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Automotivo,pneus,43.50,44.17,0.0,44.17,7,309.19,4.69,2019 - Dec
8937,2019-12-31,2020-01-04,Entrega padrão,Lara Pinto,B2C,São Paulo,São Paulo,Sudeste,Materiais de construção,encanamentos,269.52,305.19,0.1,274.67,4,1098.68,20.60,2019 - Dec
8938,2019-12-31,2020-01-04,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,19.80,26.27,0.1,23.64,2,47.28,7.68,2019 - Dec
8939,2019-12-31,2020-01-04,Entrega padrão,Cauê Martins,B2B,Osasco,São Paulo,Sudeste,Jardinagem e paisagismo,ferramentas de jardinagem,29.72,39.13,0.1,35.22,2,70.44,11.00,2019 - Dec

In [ ]:
# Pivotando a tabela (colocando os anos/meses em colunas)

vendas_mensais = df_meses.pivot_table(index = 'departamento', columns = 'meses', values = 'quantidade', aggfunc = 'sum', sort = False)
vendas_mensais

meses,2016 - Jan,2016 - Feb,2016 - Mar,2016 - Apr,2016 - May,2016 - Jun,2016 - Jul,2016 - Aug,2016 - Sep,2016 - Oct,...,2019 - Mar,2019 - Apr,2019 - May,2019 - Jun,2019 - Jul,2019 - Aug,2019 - Sep,2019 - Oct,2019 - Nov,2019 - Dec
departamento,,,,,,,,,,,,,,,,,,,,,
Jardinagem e paisagismo,161,87,277,323,270,273,348,339,549,276,...,458,415,542,490,423,561,929,617,946,989
Automotivo,45,20,46,107,81,83,91,95,154,85,...,167,87,150,170,168,136,280,205,331,252
Materiais de construção,60,23,102,69,91,114,104,101,182,94,...,107,131,172,151,162,132,282,213,312,395

In [ ]:
estilo_mensal =  vendas_mensais.style
estilo_mensal

In [ ]:
estilo_mensal.set_sticky(axis = 1)

In [ ]:
colunas = {
    'selector': '.col_heading',
    'props': 'font-weight: normal; font-family: Arial'
}
tabelas = {
    'selector': 'td,th',
    'props': 'text-align: left;'
}
index = {
    'selector': '.index_name',
    'props': 'font-weight: bold; font-family: Arial; text-align: right;'
}
estilo_mensal.set_table_styles([colunas, tabelas, index], overwrite = False)

# Missão 5: Relatório de performance

O relatório de performance é um documento muito importante para a empresa. Nele, todos que trabalham na loja podem entender como anda a empresa. Por conta disso, tabelas bem construídas são essenciais para mostrar os dados da melhor forma.

Portanto, precisamos construir uma visualização que permita entender a **relação entre tipos de clientes e modo de envio de produtos de acordo com as vendas**. Com isso, será possível destacar no relatório qual o modo de envio e quais tipos de modo de envio mais geraram ganho em vendas.

In [ ]:
df_cliente = df.pivot_table(index = 'segmento_cliente', columns = 'modo_envio', values = 'vendas',
                            aggfunc = 'sum')
df_cliente

modo_envio         24 horas  Econômica  Entrega padrão  Envio rápido
segmento_cliente
B2B               217465.60  718461.22      1884738.56     602049.40
B2C               182531.47  729174.73      2248283.69     498294.88

In [ ]:
df_cliente['Total'] = df_cliente.sum(axis = 1)
df_cliente.loc['Total'] = df_cliente.sum()
df_cliente

modo_envio,24 horas,Econômica,Entrega padrão,Envio rápido,Total
segmento_cliente,,,,,
B2B,217465.60,718461.22,1884738.56,602049.40,3422714.78
B2C,182531.47,729174.73,2248283.69,498294.88,3658284.77
Total,399997.07,1447635.95,4133022.25,1100344.28,7080999.55

In [ ]:
compra_cliente = df_cliente.style.format('{:,.2f}')
compra_cliente

In [ ]:
tabela = {
    'selector': 'td,th:not(.index_name)',
    'props': 'font-weight: normal; font-family: Arial; text-align: center; background-color: gray'
}

index = {
    'selector': '.index_name',
    'props' : 'font-weight: normal; text-align: left; font-style: italic; color: #696969'
}

compra_cliente.set_table_styles([tabela, index])

In [ ]:
compra_cliente.set_table_styles({
    'Total': [{
        'selector': 'th',
        'props': 'border-top: 1px solid #181818'
    },
    {
        'selector': 'td',
        'props': 'border-top: 1px solid #181818'
    }],
    'B2B': [{
        'selector': 'th',
        'props': 'border-top: 1px solid #181818'
    },
    {
        'selector': 'td',
        'props': 'border-top: 1px solid #181818'
    }]
}, overwrite = False, axis = 1)

In [ ]:
# Destacando a linha do B2C

compra_cliente.set_table_styles({
    'Total': [{
        'selector': '.true',
        'props': 'background-color: #509d34'
    }]
}, overwrite = False, axis = 1)

cores_coluna = pd.DataFrame(['false', 'true', 'false'], index = df_cliente['Total'].index,
                            columns = ['Total'])

compra_cliente.set_td_classes(cores_coluna)

In [ ]:
df_cliente

modo_envio,24 horas,Econômica,Entrega padrão,Envio rápido,Total
segmento_cliente,,,,,
B2B,217465.60,718461.22,1884738.56,602049.40,3422714.78
B2C,182531.47,729174.73,2248283.69,498294.88,3658284.77
Total,399997.07,1447635.95,4133022.25,1100344.28,7080999.55

In [ ]:
# Destacando a linha  Total

compra_cliente.set_table_styles({
    'Total': [{
        'selector': '.true',
        'props': 'background-color: #509d34'
    }]
}, overwrite = False, axis = 1)

cores_linha = pd.DataFrame([['false', 'false', 'true', 'false', 'false']], columns = df_cliente.columns, index = ['Total'])

compra_cliente.set_td_classes(cores_linha)